const formInputObjList = [
  {
    fieldId: "initials",
    fieldLabel: "Initials",
    fieldType: "text-input",
    width: 250,
    isRequired: true,
    // minLength: 3,
    maxLength: 5,
    isUnique: true,
  },
  {
    fieldId: "studentCode",
    fieldLabel: "Student Code",
    fieldType: "text-input",
    width: 250,
    isRequired: true,
    minLength: 3,
    // maxLength: 6,
    isUnique: true,
    // valueType: "int",
  },
  {
    fieldId: "name",
    fieldLabel: "Full Name",
    fieldType: "text-input",
    width: 250,
    isRequired: true,
    minLength: 7,
    maxLength: 20,
    isUnique: true,
  },
  {
    fieldId: "marksObtained",
    fieldLabel: "Marks Obtained",
    fieldType: "text-input",
    width: 250,
    isRequired: true,
    minValue: 0,
    maxValue: 100,
    valueType: "int", // 'float', 'string', 'boolean', 'date' - dd-mm-yyyy
  },
  {
    fieldId: "dob",
    fieldLabel: "Date Of Birth",
    fieldType: "date-picker",
    width: 120,
    isRequired: true,
  },
  {
    fieldId: "gender",
    fieldLabel: "Gender",
    fieldType: "radio",
    width: 250,
    isRequired: true,
    options: { m: "Male", f: "Female", oth: "Others" },
  },
  {
    fieldId: "emailId",
    fieldLabel: "Email ID",
    fieldType: "text-input",
    width: 250,
    isUnique: true,
    isRequired: true,
    minLength: 5,
    maxLength: 60,
  },
  {
    fieldId: "phoneNo",
    fieldLabel: "Phone No",
    fieldType: "text-input",
    width: 150,
    isUnique: true,
    isRequired: true,
    minLength: 10,
    maxLength: 10,
    minValue: 4000000000,
    maxValue: 9999999999,
    valueType: "int",
  },
  // {
  //   fieldId: "expSalary",
  //   fieldLabel: "Salary",
  //   fieldType: "text-input",
  //   width: 150,
  //   // isUnique: true,
  //   isRequired: true,
  //   minLength: 5,
  //   maxLength: 5,
  //   minValue: 20000,
  //   maxValue: 50000,
  //   valueType: "int",
  // },
  {
    fieldId: "postalAddress",
    fieldLabel: "Postal Address",
    fieldType: "text-area",
    width: 250,
    height: 5,
    isRequired: true,
    minLength: 4,
    maxLength: 300,
  },
  {
    fieldId: "stream",
    fieldLabel: "Stream",
    fieldType: "select",
    isRequired: true,
    options: {
      c: "Computer Engineering",
      i: "Information Technology",
      e: "Electrical Engineering",
      m: "Mechanical Engineering",
    },
  },
  {
    fieldId: "preferredTiming",
    fieldLabel: "Preferred Timings",
    fieldType: "multiple-select",
    width: 15,
    isRequired: true,
    options: {
      1: "10:00am - 12:00pm",
      2: "12:00pm - 02:00pm",
      3: "02:00pm - 04:00pm",
      4: "04:00pm - 06:00pm",
    },
  },
  {
    fieldId: "isActive",
    fieldType: "boolean",
    fieldLabel: "Active",
  },
  // {
  //   fieldId: "fileUpload",
  //   fieldLabel: "File",
  //   fieldType: "file",
  //   isRequired: true,
  // },
];
